// apps/desktop/src/renderer/src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { UserPresenter } from "shared/user/user.presenter";

  const userPresenter = new UserPresenter();
  let viewModel = [];

  onMount(async () => {
    await userPresenter.load((vm: unknown[]) => {
      viewModel = vm;
    });
  });
  
</script>

<div>
  <ul>
  {#each viewModel as user}
   <li>{user.firstName}</li> 
  {:else}
    <li>Loading...</li>
  {/each}
  </ul>
</div>

<style>
</style>

// apps/web/app/page.tsx
import { UserList } from "react-ui";
import { UserPresenter } from "shared/user/user.presenter";

async function getData() {
  const userPresenter = new UserPresenter();
  let viewModel = [];

  await userPresenter.load((vm) => {
    viewModel = vm;
  });

  return viewModel;
}

export default async function Page() {
  const viewModel = await getData();

  return (
    <>
      <article>
        <UserList viewModel={viewModel} />
      </article>
    </>
  );
}
